name: pre-commit

on:
  push:
    branches: [master]
  pull_request:

jobs:
  analyze_code:
    runs-on: ubuntu-latest
    steps:
    - name: Install Pre-Commit
      run: python -m pip install pre-commit
      shell: bash
    - name: Show installed packages
      run: python -m pip freeze --local
      shell: bash
    - uses: actions/cache@v5
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run Pre-Commit
      working-directory: ./backend
      run: git init && git add . && pre-commit run --show-diff-on-failure --color=always
      shell: bash
